[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

upload_port = /dev/ttyUSB0    ; CP2102
monitor_port = /dev/ttyUSB0

; Если не работает — добавь:
upload_speed = 921600
;